# Generated by Django 4.0.6 on 2022-08-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0003_alter_categoria_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
