# Generated by Django 4.0.6 on 2022-08-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0004_producto_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(default='rojo', max_length=100),
            preserve_default=False,
        ),
    ]
